services:
  web:
    build: ./httpd
    ports:
      - "8080:8080"     
    volumes:
    - 'dockvol:/shared'
  python:
    build: ./python
    command: >
      /bin/bash cp /home/eltacohero/docker/python/date.py python/
      /bin/bash python3 date.py
    volumes:
      - 'dockvol:/shared'
volumes:
  dockvol:
    driver: local            
