services:
  web:
    build: ./httpd
    ports:
      - "8080:8080"     
    volumes:
      - 'dockvol:/shared'
  python:
    build: ./python
    command: >
      /bin/bash cp /home/eltacohero/docker/python/date.py python/ && python3 date.py > /shared/index.html
    volumes:
      - 'dockvol:/shared'
volumes:
  dockvol:
    driver: local            
